name: ICONiST
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#fffffb'
    - '#727153'
    - '#dd8924'
    - '#b82e2b'
  brandStrength: 1
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
